### ISSUE TITLE
establishmentMeans mapping

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/daisie-checklist#15]
Information for `establishmentMeans` is contained in `ss_species_status`.
This is what I suggest for the mapping to the [establishmentMeans vocabulary]():

ss_species_status | establishmentMeans
--- | ---
Alien | introduced
Cryptogenic | uncertain
Naturalized | naturalised
Casual | naturalised
Alien_invasive | invasive

I chose to map `casual` to `naturalised`, based on the argument by @timadriaens [here](https://github.com/trias-project/alien-plants-belgium/issues/52#issuecomment-355976672)

**Comment by timadriaens** [comment]
you mean naturalized to casual. I think perhaps it's best to bring them in line with Blackburn et al. as in the [new darwin core proposal](https://docs.google.com/document/d/1zPSiqH2HOyJ2HbIVP-k5CmfR7rJZ8rHgUT8DmIl-J1w/edit#heading=h.bydoa31slhuz) of @qgroom ? 
So naturalized to _introducedNaturalised_, Alien_invasive to _introducedInvasive_?

**Comment by qgroom** [comment]
Actually, in the paper we propose vagrant for casual (they are synonyms). We do maintain introducedInvasive, but we discourage people from using it, because we would prefer people use degreeOfEstablishment. We only maintain it to keep back compatibly of data on GBIF.

ss_species_status | establishmentMeans
--- | ---
Alien | introduced
Cryptogenic | uncertain
Naturalized | introduced
Casual | vagrant
Alien_invasive | introduced

**Comment by DavidRoy** [comment]
@LienReyserhove are we mapping to degreeOfEstablishment for DAISIE?  If so, I'd be ok with this suggestion by @qgroom.  If not, I would prefer your original mapping of Alien_invasive (DAISIE) to invasive (GBIF) to retain this information from DAISIE
